export const t = {
  uz: {
    profileTitle: "Profil",
    loginTelegramOnly: "Iltimos, Telegram mini ilovada kiring.",
    failedLoadProfile: "Profil yuklanmadi",
    inviteStaff: "Xodim taklif qilish",
    generatingInvite: "Taklif yaratilmoqda…",
    support: "Yordam",
    logout: "Chiqish",
    logoutConfirm: "Chiqishni tasdiqlaysizmi?",
    staff: "Xodimlar",
    staffLoadError: "Xodimlar ro‘yxati yuklanmadi",
    noStaffYet: "Hozircha xodim yo‘q",
    remove: "O'chirish",
    removeStaffTitle: "Bu xodimni o'chirishni xohlaysizmi?",
    removeStaffLossSuffix: "ushbu biznesga kirish huquqidan mahrum bo‘ladi.",
    leaveBusiness: "Biznesni tark etish",
    leaveTitle: "Biznesni tark etishni xohlaysizmi?",
    leaveSubtitle: "Qayta kirish uchun qaytadan kirish yoki yangi taklif kerak bo‘ladi.",
    cancel: "Bekor qilish",
    leave: "Tark etish",
    ourBusiness: "Biznesimiz",
    inviteShareLine1: "Jamoamizga qo‘shiling:",
    inviteShareLine3: "Quyidagi havolani bosing 👇",
    failedInvite: "Taklif havolasi yaratilmadi",
    inviteCopied: "Taklif havolasi nusxalandi",
    copyInvitePrompt: "Taklif havolasini nusxalang:",
    couldNotLeave: "Biznesni tark etib bo‘lmadi",
    failedRemoveStaff: "Xodimni o'chirib bo‘lmadi",
    staffRemoved: "Xodim o'chirildi",
    roleOwner: "Bosh egasi",
    roleStaff: "Xodim",
    userFallback: "Foydalanuvchi",

    navHome: "Asosiy",

    loginWelcomeTitle: "Stamply ga xush kelibsiz",
    loginSubtitle: "Davom etish uchun kiring",
    loginContinueTelegram: "Telegram bilan kirish",
    loginTermsNote:
      "Davom etish orqali Telegram orqali autentifikatsiyadan foydalanishga rozilik bildirasiz.",
    loginOpenInTelegram: "Davom ettirish uchun Telegram ichidan oching.",
    loginFailed: "Kirish amalga oshmadi. Qayta urinib ko‘ring.",

    registerCreatingTitle: "Biznes yaratilmoqda…",
    registerCreatingSubtitle: "Sozlash tugallanmoqda. Iltimos, kuting.",
    registerTitle: "Biznesingizni yarating",
    registerSubtitle: "Mijozlaringiz ko‘radigan ma’lumot",
    registerBizNamePh: "Biznes nomi *",
    registerPhonePh: "Telefon *",
    registerAddressPh: "Manzil (ixtiyoriy)",
    registerTypePh: "Biznes turi (ixtiyoriy)",
    registerCreating: "Yaratilmoqda…",
    registerCreateBusiness: "Biznesni yaratish",
    registerFailed: "Biznes yaratilmadi. Qayta urinib ko‘ring.",

    welcomeBackToast: "Xush kelibsiz 👋",

    homeLoading: "Yuklanmoqda…",
    homeDashboardLoadHint: "Boshqaruv paneli yuklanmoqda…",
    homeFailedDashboard: "Boshqaruv paneli yuklanmadi",
    homePending: "Kutilmoqda",
    homeCustomers: "Mijozlar",
    homeVisitsToday: "Bugungi tashriflar",
    homeRecentActivity: "So‘nggi hodisalar",
    homeToday: "Bugun",
    homeNoActivity: "Hozircha hodisalar yo‘q",
    homeRewards: "Mukofotlar",
    homeLoadingRewards: "Yuklanmoqda…",
    homeNoRewardsToday: "Bugun mukofot yo‘q",
    homeRewardRedeemed: "ijro etildi",
    homeRewardUnlocked: "ochiq",
    homeRewardOther: "mukofot",
    homePendingRequests: "Kutilayotgan so‘rovlar",
    homeClose: "Yopish",
    homeNoPending: "Kutilayotgan so‘rov yo‘q",
    homeApprove: "Tasdiqlash",
    homeDone: "Tayyor",
    homeScanQr: "QR skanerlash",
    homeDownload: "Yuklab olish",
    homeFailed: "Muvaffaqiyatsiz",
    homeApproved: "Tasdiqlandi",
    homeRewardUnlockedToast: "Mukofot ochildi 🎉",
    homeBusinessFallback: "Biznes",
    homeApproveError: "Xatolik",
    homeLoadingAria: "Yuklanmoqda",

    customersFailed: "Mijozlar yuklanmadi",
    customersSearchPh: "Ism bo‘yicha qidirish",
    customersTotalLabel: "umumiy",
    customersEmpty: "Hozircha mijozlar yo‘q",

    visitsTitle: "Tashriflar",
    visitsFailed: "Tashriflar yuklanmadi",
    visitsSearchPh: "Mijozni qidirish",
    visitsGiveStamp: "Shtamp berish",
    visitsRecent: "So‘nggi tashriflar",
    visitsNoRecent: "So‘nggi tashrif yo‘q",
    visitsStampAdded: "Shtamp qo‘shildi",
    visitsMetaVisits: "tashrif",
    visitsMetaStamps: "shtamp",
    visitsRecentReward: "mukofot ochildi",
    visitsRecentStamp: "shtamp qo‘shildi",
    visitsModalTitle: "🎉 Mukofot ochildi!",
    visitsModalSubtitle: "Mijoz 8 shtampga ega bo‘ldi",
    visitsModalButton: "Mukofot berish",
    visitsRewardGiven: "Mukofot berildi",

    rewardsFailed: "Mukofotlar yuklanmadi",
    rewardsEmpty: "Hozircha mukofot yo‘q",
    rewardsRedeem: "Yechib olish",
    rewardsPending: "Kutilayotgan mukofotlar",

    activityStampAdded: "Shtamp qo‘shildi",
    activityStampsAdded: "Shtamplar qo‘shildi",
    activityRewardUnlocked: "Mukofot ochildi",
    activityRewardRedeemed: "Mukofot ishlatildi",
    activityVisitApproved: "Tashrif tasdiqlandi",
    activityVisitRecorded: "Tashrif qayd etildi",
    activityRewardIssued: "Mukofot berildi",

    customerDetailInvalid: "Mijoz topilmadi",
    customerDetailBack: "← Mijozlar",
    customerDetailLoadError: "Mijoz yuklanmadi",
    customerDetailHeading: "Mijoz",
    customerDetailNoVisits: "Hozircha tashrif yo‘q",
    customerDetailNoRewardsList: "Hozircha mukofot yo‘q",
    customerDetailRewardLine: "Mukofot №",
    customerRewardExpired: "Muddati o‘tgan",
    customerRewardCancelled: "Bekor qilingan",
  },
  ru: {
    profileTitle: "Профиль",
    loginTelegramOnly: "Войдите через мини-приложение Telegram.",
    failedLoadProfile: "Не удалось загрузить профиль",
    inviteStaff: "Пригласить сотрудника",
    generatingInvite: "Создание приглашения…",
    support: "Поддержка",
    logout: "Выйти",
    logoutConfirm: "Выйти из аккаунта?",
    staff: "Сотрудники",
    staffLoadError: "Не удалось загрузить список сотрудников",
    noStaffYet: "Пока нет сотрудников",
    remove: "Удалить",
    removeStaffTitle: "Удалить этого сотрудника?",
    removeStaffLossSuffix: "потеряет доступ к этому бизнесу.",
    leaveBusiness: "Покинуть бизнес",
    leaveTitle: "Покинуть этот бизнес?",
    leaveSubtitle: "Чтобы вернуться, нужно снова войти или использовать новое приглашение.",
    cancel: "Отмена",
    leave: "Покинуть",
    ourBusiness: "Наш бизнес",
    inviteShareLine1: "Присоединяйтесь к нашей команде:",
    inviteShareLine3: "Нажмите на ссылку ниже 👇",
    failedInvite: "Не удалось создать ссылку-приглашение",
    inviteCopied: "Ссылка скопирована",
    copyInvitePrompt: "Скопируйте ссылку:",
    couldNotLeave: "Не удалось покинуть бизнес",
    failedRemoveStaff: "Не удалось удалить сотрудника",
    staffRemoved: "Сотрудник удалён",
    roleOwner: "Владелец",
    roleStaff: "Сотрудник",
    userFallback: "Пользователь",

    navHome: "Главная",

    loginWelcomeTitle: "Добро пожаловать в Stamply",
    loginSubtitle: "Войдите, чтобы продолжить",
    loginContinueTelegram: "Продолжить через Telegram",
    loginTermsNote:
      "Продолжая, вы соглашаетесь на аутентификацию через Telegram.",
    loginOpenInTelegram: "Откройте приложение внутри Telegram, чтобы продолжить.",
    loginFailed: "Не удалось войти. Попробуйте ещё раз.",

    registerCreatingTitle: "Создаём бизнес…",
    registerCreatingSubtitle: "Завершаем настройку. Подождите.",
    registerTitle: "Создайте бизнес",
    registerSubtitle: "Эти данные увидят ваши клиенты",
    registerBizNamePh: "Название бизнеса *",
    registerPhonePh: "Телефон *",
    registerAddressPh: "Адрес (необязательно)",
    registerTypePh: "Тип бизнеса (необязательно)",
    registerCreating: "Создание…",
    registerCreateBusiness: "Создать бизнес",
    registerFailed: "Не удалось создать бизнес. Попробуйте ещё раз.",

    welcomeBackToast: "С возвращением 👋",

    homeLoading: "Загрузка…",
    homeDashboardLoadHint: "Загрузка панели…",
    homeFailedDashboard: "Не удалось загрузить панель",
    homePending: "Ожидают",
    homeCustomers: "Клиенты",
    homeVisitsToday: "Визиты сегодня",
    homeRecentActivity: "Недавняя активность",
    homeToday: "Сегодня",
    homeNoActivity: "Пока нет активности",
    homeRewards: "Награды",
    homeLoadingRewards: "Загрузка…",
    homeNoRewardsToday: "Сегодня без наград",
    homeRewardRedeemed: "использовано",
    homeRewardUnlocked: "доступно",
    homeRewardOther: "награда",
    homePendingRequests: "Ожидающие запросы",
    homeClose: "Закрыть",
    homeNoPending: "Нет ожидающих",
    homeApprove: "Подтвердить",
    homeDone: "Готово",
    homeScanQr: "Сканировать QR",
    homeDownload: "Скачать",
    homeFailed: "Не удалось",
    homeApproved: "Подтверждено",
    homeRewardUnlockedToast: "Награда открыта 🎉",
    homeBusinessFallback: "Бизнес",
    homeApproveError: "Ошибка",
    homeLoadingAria: "Загрузка",

    customersFailed: "Не удалось загрузить клиентов",
    customersSearchPh: "Поиск по имени или телефону",
    customersTotalLabel: "Всего",
    customersEmpty: "Пока нет клиентов",

    visitsTitle: "Визиты",
    visitsFailed: "Не удалось загрузить визиты",
    visitsSearchPh: "Поиск клиента",
    visitsGiveStamp: "Выдать штамп",
    visitsRecent: "Недавние визиты",
    visitsNoRecent: "Нет недавних визитов",
    visitsStampAdded: "Штамп добавлен",
    visitsMetaVisits: "виз.",
    visitsMetaStamps: "шт.",
    visitsRecentReward: "награда открыта",
    visitsRecentStamp: "штамп добавлен",
    visitsModalTitle: "🎉 Награда открыта!",
    visitsModalSubtitle: "Клиент набрал 8 штампов",
    visitsModalButton: "Выдать награду",
    visitsRewardGiven: "Награда выдана",

    rewardsFailed: "Не удалось загрузить награды",
    rewardsEmpty: "Пока нет наград",
    rewardsRedeem: "Обменять",
    rewardsPending: "Ожидающие награды",

    activityStampAdded: "Штамп добавлен",
    activityStampsAdded: "Штампы добавлены",
    activityRewardUnlocked: "Награда открыта",
    activityRewardRedeemed: "Награда использована",
    activityVisitApproved: "Визит подтверждён",
    activityVisitRecorded: "Визит записан",
    activityRewardIssued: "Награда выдана",

    customerDetailInvalid: "Клиент не найден",
    customerDetailBack: "← К клиентам",
    customerDetailLoadError: "Не удалось загрузить клиента",
    customerDetailHeading: "Клиент",
    customerDetailNoVisits: "Пока нет визитов",
    customerDetailNoRewardsList: "Пока нет наград",
    customerDetailRewardLine: "Награда №",
    customerRewardExpired: "Истекла",
    customerRewardCancelled: "Отменена",
  },
} as const;

export type ProfileLang = keyof typeof t;
